'use strict';

/**
 * pulse.js — the weekly memory pulse.
 *
 * A short, templated brief over memory.md that is pushed to the operator
 * instead of waiting to be recalled: what entered the brain this week, which
 * standing decisions are getting old, and one "is this still true?" question
 * with a yes/no answer path. Nothing in the brief is generated by a model;
 * every quoted span is an entry's own content and every sentence around it is
 * a fixed template. Ported from the fred-vision pulse (2026-09-02).
 *
 * Pure planning/rendering lives here; scripts/pulse.js does the I/O.
 */

const QUIET_DAYS = 45;      // a decision/constraint this old with no lifecycle field is "standing"
const ASK_MIN_AGE_DAYS = 30; // never ask about something younger than this
const ASKABLE = new Set(['DECISION', 'CONSTRAINT', 'PATTERN']);
const SAMPLE_MAX = 4;
const QUIET_MAX = 2;
const QUOTE_MAX_WORDS = 40;

const dayOf = (iso) => (iso || '').slice(0, 10);
const daysBetween = (a, b) => Math.floor((Date.parse(dayOf(b)) - Date.parse(dayOf(a))) / 86400000);
const isLive = (e) => !e.supersededBy && !e.stale;

/** First sentence of an entry's content, capped at QUOTE_MAX_WORDS. */
function trimQuote(content) {
  const flat = (content || '').replace(/\s+/g, ' ').trim();
  const first = flat.split(/(?<=[.!?])\s+/)[0] || flat;
  const words = first.split(' ');
  return words.length > QUOTE_MAX_WORDS ? words.slice(0, QUOTE_MAX_WORDS).join(' ') + ' ...' : first;
}

/**
 * Decide what this week's pulse says.
 * @param {Array} entries - readMemory() output
 * @param {{ now: string, since: string, asked?: Array<{hash: string, date: string, answer?: string}> }} opts
 */
function pulsePlan(entries, { now, since, asked = [] }) {
  const live = entries.filter(isLive);
  const added = live
    .filter(e => dayOf(e.addedAt || e.date) >= since && dayOf(e.addedAt || e.date) <= now)
    .sort((a, b) => (b.addedAt || b.date).localeCompare(a.addedAt || a.date));

  const byCategory = {};
  for (const e of added) byCategory[e.category] = (byCategory[e.category] || 0) + 1;

  // Samples: decisions first, then constraints/patterns, newest first.
  const rank = { DECISION: 0, CONSTRAINT: 1, PATTERN: 2 };
  const sample = [...added]
    .sort((a, b) => (rank[a.category] ?? 9) - (rank[b.category] ?? 9) || (b.addedAt || b.date).localeCompare(a.addedAt || a.date))
    .slice(0, SAMPLE_MAX);

  const askedHashes = new Set(asked.map(a => a.hash));
  const standing = live
    .filter(e => ASKABLE.has(e.category) && daysBetween(e.addedAt || e.date, now) >= QUIET_DAYS)
    .sort((a, b) => (a.addedAt || a.date).localeCompare(b.addedAt || b.date));
  const quiet = standing.filter(e => !askedHashes.has(e.contentHash)).slice(0, QUIET_MAX);

  // One question: oldest askable entry never asked before. Never nag.
  const ask = live
    .filter(e => ASKABLE.has(e.category) && daysBetween(e.addedAt || e.date, now) >= ASK_MIN_AGE_DAYS && !askedHashes.has(e.contentHash))
    .sort((a, b) => (a.addedAt || a.date).localeCompare(b.addedAt || b.date))[0] || null;

  const fallback = !added.length && !quiet.length && !ask
    ? [...live].sort((a, b) => (a.addedAt || a.date).localeCompare(b.addedAt || b.date))[0] || null
    : null;

  return { added: added.length, byCategory, sample, standing: standing.length, quiet, ask, fallback, total: live.length };
}

const monthDay = (iso) => new Date(dayOf(iso) + 'T00:00:00Z').toLocaleDateString('en-US', { month: 'long', day: 'numeric', timeZone: 'UTC' });
const cats = (byCategory) => Object.entries(byCategory).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${v} ${k}`).join(', ');

/** Deterministic markdown. Second person. Nothing generated. */
function pulseText(plan, { now, since }) {
  const L = [];
  L.push(`# Memory pulse, week of ${monthDay(now)}`);
  L.push('');
  L.push(`_${dayOf(since)} to ${dayOf(now)} · ${plan.total} live entries_`);
  L.push('');
  if (plan.added === 0) {
    L.push('Nothing new entered memory this week.');
  } else {
    L.push(`**${plan.added} entries entered memory this week** (${cats(plan.byCategory)}).`);
    L.push('');
    for (const e of plan.sample) L.push(`- ${e.category} · ${monthDay(e.addedAt || e.date)}: ${trimQuote(e.content)}`);
  }
  L.push('');
  if (plan.quiet.length) {
    L.push(`**Standing for ${QUIET_DAYS}+ days** (${plan.standing} total, oldest first):`);
    L.push('');
    for (const e of plan.quiet) L.push(`- ${e.category} · ${monthDay(e.addedAt || e.date)}: ${trimQuote(e.content)}`);
    L.push('');
  }
  if (plan.ask) {
    const e = plan.ask;
    L.push('## One question');
    L.push('');
    L.push(`On ${monthDay(e.addedAt || e.date)} this went into memory as a ${e.category}:`);
    L.push('');
    L.push(`> ${trimQuote(e.content)}`);
    L.push('');
    L.push(`Is that still true? Answer with \`/pulse yes\` or \`/pulse no\` (no marks it stale). Entry \`${e.contentHash}\`.`);
    L.push('');
  }
  if (plan.fallback) {
    const e = plan.fallback;
    L.push('## Worth hearing again');
    L.push('');
    L.push(`> ${trimQuote(e.content)}`);
    L.push('');
  }
  L.push(`_Templated from memory.md; nothing here was generated. Answering the question is the only step that needs you._`);
  return L.join('\n') + '\n';
}

module.exports = { pulsePlan, pulseText, trimQuote, QUIET_DAYS, ASK_MIN_AGE_DAYS, ASKABLE };
